### ISSUE TITLE
Convert trusted networks to on-demand activation

### ISSUE THREAD

**Issue by keeshux** [passepartoutvpn/passepartout-apple#119]
Like WireGuard does, with only/except matching policy.

**Comment by fumoboy007** [comment]
Is this related to not being able to explicitly connect on a trusted network?

**Comment by keeshux** [comment]
Exactly, that's the idea.

**Comment by alexw1982** [comment]
would that also add the ability to connect on-demand in the iOS sense, meaning by app. This would be awesome as well. Meaning a VPN connection is established when a specific app is used (and ideally only that traffic is routed via this specific tunnel)

**Comment by keeshux** [comment]
Nope, it's not related.

**Comment by alexw1982** [comment]
I was referencing the function outlined here

**Comment by keeshux** [comment]
I see, but it has nothing to do with what you expect it to accomplish!

**Comment by alexw1982** [comment]
Does it make sense to open the topic for discussion as a future feature? I do not know the level of interest for this. I would imagine that everyone that uses the VPN to bypass geo restrictions on certain apps (hulu, cnn and many other apps) would love this feature ...

**Comment by keeshux** [comment]
I understand the need and also like the feature, but I wouldn't do it unless Apple makes it native. Not in OpenVPN at least. If WireGuard supports it, that's another story for later.

**Comment by alexw1982** [comment]
okay, my understanding was that is is nativly supported (at least for ikev2 and ipsec)

**Comment by keeshux** [comment]
I mean that "on demand rules" are not rules for a "per app VPN".

**Comment by mikicof** [comment]
I’ve seen on other vpn apps that you can include a list of domains to be added to the connect on demand rules so it will only connect to the vpn when any connection is done to them…
That would be great for my home network, don’t know if related to this or better on another thread.

**Comment by juev** [comment]
This function is present on [Shadowrocket](https://apps.apple.com/us/app/shadowrocket/id932747118).

It great function. For example, I setup disconnect from vpn when my iPhone will sleep, and connect to vpn when I open domain from list. Another one, we can setup vpn only for specific domains. All other request will use direct connection.

When we activate vpn only when we open specific domains, we will economy our battery energy.
