### ISSUE TITLE
Can't update to 1.13.1. App is no longer available in the iOS store error message.

### ISSUE THREAD

**Issue by bolducd** [passepartoutvpn/passepartout-apple#168]
![IMG_1262](https://user-images.githubusercontent.com/73037674/103654875-784ae500-4f34-11eb-9f6f-a2aedfb63679.jpg)

**Comment by artem-sidorenko** [comment]
Same for me, AppStore Germany

**Comment by keeshux** [comment]
https://www.reddit.com/r/passepartout/comments/ko7p3p/i_made_the_ios_update_1130_temporarily/?utm_source=share&utm_medium=ios_app&utm_name=iossmf

**Comment by keeshux** [comment]
Are you guys on 1.12.1 or older? Because, given the lack of beta testers, it would be infinitely helpful if you could confirm that upgrading to 1.14.0 is fine before I officially release it.

If so, please message me on beta@passepartoutvpn.app and we can finally unlock this tedious release.

**Comment by bolducd** [comment]
Main phone on 1.13 (the one offering me the update to 1.13.1 with the error message can't upgrade)  but I still have an iPhone and an iPad on 1.12.1. I'm sending you an email for the beta.
