### ISSUE TITLE
Can't use connection with DNS over HTTPS (+Mullvad)

### ISSUE THREAD

**Issue by sander1** [passepartoutvpn/passepartout-apple#171]
Hi!

I tried to setup DNS over HTTPS in the latest version of Passepartout (which is `1.15.0 (2617)` as of now). My VPN provider is Mullvad, and I have read about the DNS issue where Mullvad hijacks DNS on the default endpoints ([Mullvad ignores my custom DNS settings](https://passepartoutvpn.app/faq/#mullvad-ignores-my-custom-dns-settings)).

So I chose UDP port 1400 for _Endpoint_ and Custom DNS as _Preset_:

![1-main](https://user-images.githubusercontent.com/104684/107581233-aedce500-6bef-11eb-8ea5-3a2d5347d511.jpg) ![2-endpoint](https://user-images.githubusercontent.com/104684/107581238-b13f3f00-6bef-11eb-871d-354ccca586ee.jpg) ![3-preset](https://user-images.githubusercontent.com/104684/107581240-b2706c00-6bef-11eb-938f-36f329d342fd.jpg)

Now in _Network settings_, when I set DNS to Manual, choose HTTPS as protocol and enter my NextDNS endpoint, like so:

![4-network-settings-doh-dns](https://user-images.githubusercontent.com/104684/107581613-3e829380-6bf0-11eb-8ccb-694fbe7d1d6d.jpg)

...it doesn't work. A connection is made, but I can't browse the internet.

However, if I choose Cleartext as the protocol and enter the NextDNS IP addresses as endpoints (ipv6 in this case), like so:

![5-network-settings-cleartext-dns](https://user-images.githubusercontent.com/104684/107581783-7c7fb780-6bf0-11eb-8716-3e2744591089.jpg)

...everything works perfectly fine and those DNS servers are being used (according to the NextDNS dashboard and https://www.dnsleaktest.com/).

Now I was wondering if this is maybe because when using DNS over HTTPS, the first DNS request to find the IP for the DoH hostname is usually done by so called bootstrap DNS servers (over plain DNS). Since I can't setup those bootstrap DNS, is this why I can't use NextDNS DoH in Passepartout?

![DoH_with_bootstrap2](https://user-images.githubusercontent.com/104684/107583025-3cb9cf80-6bf2-11eb-850b-4b6d0b584747.jpg)

---
OS: iOS 14.4

**Comment by keeshux** [comment]
@sander1 could you repeat the same test with CloudFlare DNS endpoint?

IIRC: https://cloudflare-dns.com/dns-query

**Comment by sander1** [comment]
> @sander1 could you repeat the same test with CloudFlare DNS endpoint?
> 
> IIRC: https://cloudflare-dns.com/dns-query

I've tried (that is indeed the correct address), but unfortunately it also doesn't work. I've attached a debug log, which might be of some help?

[debug-20210211-011434.txt](https://github.com/passepartoutvpn/passepartout-apple/files/5962471/debug-20210211-011434.txt)

**Comment by keeshux** [comment]
Then I'm afraid that the limitation might be coming from Mullvad. I have no issues with CloudFlare.

**Comment by sander1** [comment]
I've now checked with ProtonVPN + Cloudflare, but same issue unfortunately. I currently don't have access to other VPNs but I'll ask around to see if others can check. Maybe I'm the only one with this problem - let's hope so :-)

**Comment by keeshux** [comment]
> I've now checked with ProtonVPN + Cloudflare, but same issue unfortunately. I currently don't have access to other VPNs but I'll ask around to see if others can check. Maybe I'm the only one with this problem - let's hope so :-)

I must say I’ve probably tested this only on my server, due to not having a public service subscription. Or maybe I have one, I’Ill test it right away.

**Comment by keeshux** [comment]
Okay, gotcha. There _is_ an issue.

Let me know if this temporary hack works:

- Set “Cleartext” with the bootstrap servers you mean to use with DoH
- Set “HTTPS” with the https address (bootstrap servers will disappear from UI)
- Reconnect

**Comment by sander1** [comment]
Sorry to bother you again, but it still doesn't work. As an example, I set the plain text DNS address to `9.9.9.9` and the DoH server to NextDNS. Am I correct in thinking that `9.9.9.9` should be used as a bootstrap DNS to find the IP address for the host `dns.nextdns.io`? And after that initial request all other DNS requests are sent over DoH?

![IMG_8579](https://user-images.githubusercontent.com/104684/107891646-e1e8e680-6f17-11eb-9a4c-19f52c1dac2d.jpg)

**Comment by keeshux** [comment]
You must contact Mullvad to learn if custom DoH is supported at all before reopening this issue.

**Comment by sander1** [comment]
I will shoot them an email but to be honest I'm pretty sure support for DNS over HTTPS doesn't have anything to do with VPN, since it's just HTTPS requests. It's the OS or an app that makes the decision to use DoH, that can't be changed or blocked by the VPN settings.

To clear something else up, can you please tell me what the "Address" fields do when using DoH? Is it bootstrap DNS servers, is it fallback if DoH doesn't work, or is it something else? It's not quite clear from the UI.

Thanks for your time, and I love your app! Just wishing I could get this to work so I can use certain DNS providers that offer blocklists.

**Comment by keeshux** [comment]
> I will shoot them an email but to be honest I'm pretty sure support for DNS over HTTPS doesn't have anything to do with VPN, since it's just HTTPS requests. It's the OS or an app that makes the decision to use DoH, that can't be changed or blocked by the VPN settings.

You may say the same for plain DNS, yet you know yourself that Mullvad is able to override your setting on the other endpoint.

> To clear something else up, can you please tell me what the "Address" fields do when using DoH? Is it bootstrap DNS servers, is it fallback if DoH doesn't work, or is it something else? It's not quite clear from the UI.

Truth is Apple doesn’t say a thing about what the “servers” argument exactly means in DoH/DoT.

https://developer.apple.com/documentation/networkextension/nednssettings/1406478-init

Test your own server.

**Comment by sander1** [comment]
Contacted Mullvad, got a quick response:

> Hello,
> 
> We do not block DoT or DoH, they should work as long as they go via the
> VPN tunnel.
> 
> Best regards,
> 

In the mean time I retried the combination ProtonVPN + Cloudflare DoH + address `9.9.9.9`, but without luck. My home VPN server is currently Wireguard only, but I'll see if I can setup a VM with OpenVPN to test.

**Comment by keeshux** [comment]
Use 1.1.1.1 with CloudFlare then let me know.

**Comment by sander1** [comment]
I finally have had some time to test some more. The conclusion is that with DoH (DoT probably too) you need to set 2 things:
1. The dns query URL of the DoH provider
2. At least 1 IP address in the `Address` field. This IP address needs to be valid for the hostname used in the address (it is not used as a bootstrap DNS)

Pros:
- Network maintainers can't block DoH/DoT based on hostnames (they can only block it by having specific IP addresses blacklisted)

Cons:
- You need to find out or know the IP addresses of a provider
- You can only use DoH/DoT if the IP addesses of your provider are static (so you can't for example self host at home if your ISP works with dynamic IPs - Dynamic DNS isn't going to work here).

### Cloudflare
URL: `https://cloudflare-dns.com/dns-query`
IPs:
- `1.1.1.1`
- `1.0.0.1`
- `2606:4700:4700::1111`
- `2606:4700:4700::1001`

### Quad9
URL: `https://dns.quad9.net/dns-query`
IPs:
- `9.9.9.9`
- `149.112.112.112`
- `2620:fe::fe`
- `2620:fe::fe:9`

### NextDNS
URL: `https://dns.nextdns.io/<your ID here>`
IPs:
- `45.90.28.0`
- `45.90.30.0`
- `2a07:a8c0::`
- `2a07:a8c1::`
