### ISSUE TITLE
Question: How to be sure that Passepartout does not route all IPv4 traffic through the VPN?

### ISSUE THREAD

**Issue by XavierLeTohic** [passepartoutvpn/passepartout-apple#172]
Hi, at work we usually use TunnelBlick and import a `.ovpn` file, on TunnelBlick's settings there is an option `Route all IPv4 traffic through the VPN` unchecked by default.

How can I be sure that Passepartout does not route all IPv4 traffic through the VPN? 

Thank you!

**Comment by keeshux** [comment]
Hi Xavier. A simple test is browsing something like https://iplocation.com and see what IP pops up, depending on "Network settings > Default gateway > IPv4" being enabled or disabled.

Originally I had the test inside the app, but it may raise some privacy concerns (disclosing own IP defeats the purpose of using a VPN for many people).

**Comment by XavierLeTohic** [comment]
Thank you for your quick answer, unfortunately enabling IPv4 from `Default gateway` tab makes all websites unreachable 😕

**Comment by keeshux** [comment]
Well, it all depends if your VPN can act as default gateway. Also check DNS.
