### ISSUE TITLE
Add service support for OpenVPN Cloud

### ISSUE THREAD

**Issue by th3rring** [passepartoutvpn/passepartout-apple#174]
Tried using Passepartout to connect to an OpenVPN Cloud server with a device .ovpn file but didn’t have any luck. Without exception, I’m getting an authentication failure. I started by using the username and password that allows me to log in with the OpenVPN Connect client. After trying the direct username reported with a successful connection in the OpenVPN Connect app, changing the OpenVPN Cloud settings to allow no authentication, and attempting all other credential options I have, I’m pretty stuck here.

As it says on the FAQ, I think there is a unique credential format that OpenVPN Cloud uses that I can’t figure out. It’d be great if it could be added as a provided service in-app. I’d love to be able to replace the first-party app with Passepartout.

**Comment by keeshux** [comment]
Hi, keep posting any info you may come up with, because AFAIC I don't have -nor will- any access to such a provider. If you feel like sharing parameters/credentials for me to test, send me an e-mail.

**Comment by keeshux** [comment]
Closing for no feedback.
