### ISSUE TITLE
No support for external file

### ISSUE THREAD

**Issue by telefonosuci** [passepartoutvpn/passepartout-apple#176]
Looks like there is no suppor for external file .crt

Is it a feature that will come with next releases ?

**Comment by keeshux** [comment]
No, sorry.

**Comment by keeshux** [comment]
Oh well, maybe for macOS.

**Comment by keeshux** [comment]
I gave a shot to this, but recent macOS won't let me read a file that the user doesn't give explicit permission to (e.g. through the file browser). That is an issue when trying to read files referenced by the main .ovpn configuration via relative path. Haven't found a way around this yet.

**Comment by ulope** [comment]
Why not make the user pick the files one by one?

**Comment by keeshux** [comment]
Sure, it is an option, but for that you must:

- Parse the .ovpn first to get the external file references
- Request access to the files
- Parse the .ovpn again

PRs are welcome.
