### ISSUE TITLE
VPN Profile is removed when adding trusted wifi

### ISSUE THREAD

**Issue by alexw1982** [passepartoutvpn/passepartout-apple#178]
I am experiencing a strange issue on my iPhone XR running the latest 14.4.2 (but is was already present in the previous iOS 14.x.
I set up my vpn config via a ovpn file (pfsense openvpn connection). At some point this month or last month the iOS VPN configuration disappeared. The profile is still in passepartout and I am able to connect when I hit the Enabled toggle switch in my host config inside the app. Then the VPN configuration is readded to iOS and I connect, disconnect and re-connecr with any issue - also across reboots. But as soon as I add a Wifi to the trusted networks (without toggling the switch to trusted) the VPN configuration gets removed from iOS VPN configurations - when I reopen Passepartout the Wifi also disappeared from the Trusted Networks list. 

I am only experiencing this on the above mentioned device. Other devices (iPhone 5s, iPhone 11, iPad Air 2020) work fine. I tried removing and readding the ovpn config as well as removing and reinstalling the app without any luck...

**Comment by keeshux** [comment]
Are you 100% sure you're using the same/latest version of the app everywhere?

**Comment by alexw1982** [comment]
Yes. All running 1.15.1 (2630)

**Comment by keeshux** [comment]
Closing because this might have been fixed a while ago (not 100% sure).

**Comment by alexw1982** [comment]
FYI Problem still exists for me …

**Comment by keeshux** [comment]
Because it's fixed in the next milestone (forgot to add it).

**Comment by alexw1982** [comment]
That’s great news ! Thanks
