### ISSUE TITLE
Add AirVPN to providers

### ISSUE THREAD

**Issue by x13a** [passepartoutvpn/passepartout-apple#180]
What do you think of adding [AirVPN](https://airvpn.org) to providers?

**Comment by keeshux** [comment]
Incompatible.

**Comment by etrademark** [comment]
Can we get back to this? AirVPN's API is fairly simple and I don't see why it's "incompatible". 

cURL command for recieveing an OpenVPN file with server located in the United States
```
curl -H "API-KEY: REDACTED" "https://airvpn.org/api/generator/?protocols=openvpn_3_udp_443&servers=us"
```
or in HTTP:

```
GET /api/generator/?protocols=openvpn_3_udp_443&servers=us HTTP/1.1
Host: airvpn.org
Accept: */*
API-KEY: REDACTED
```

And for specific servers:

Or wireguard and specific server
```
GET /api/generator/?protocols=wireguard_3_udp_1637&servers=beemim HTTP/1.1
```

Continent
```
GET /api/generator/?protocols=wireguard_3_udp_1637&servers=oceania HTTP/1.1
```

Earth `servers=earth`

[Here](https://airvpn.org/generator/) are all the names of the servers. I'm unsure if you can get all server names but you can check all checkboxes, cURL it and get a format like this:

```json
"options-diff": {
        "protocols": "openvpn_3_udp_443,openvpn_3_tcp_443,wireguard_3_udp_1637",
        "servers": "oceania,earth,beemim",
}
```

if a API key would assist development I can probably provide one temporarily.

**Comment by keeshux** [comment]
@etrademark if it's that simple, I suggest you take the time to read [how to integrate it](https://github.com/partout-io/passepartout/blob/master/api/README.md) and submit a pull request.
