### ISSUE TITLE
Automatic connection of VPN tunnel in order of profile?

### ISSUE THREAD

**Issue by KINGAWESOME266** [passepartoutvpn/passepartout-apple#189]
I have setup 2 OpenVPN Servers with failover in the client. I have the following ports setup: TCP 443 and UDP 1194. 

I put the UDP 1194 VPN in the top of the profile, with TCP 443 on the following line. I would like the Passepartout VPN client to use the specific order, as I want the TCP 443 to be used ONLY IF the connection on UDP 1194 is blocked. 

Would this be possible to implement, or is it too complicated?

**Comment by keeshux** [comment]
It's that way already.

**Comment by altshiftzero** [comment]
unless, iirc, you have the `remote-random` option set in the ovpn file, which does what it says it does.
