### ISSUE TITLE
Mullvad server list update iOS

### ISSUE THREAD

**Issue by prentakias** [passepartoutvpn/passepartout-apple#197]
mullvad recently upgraded its servers worldwide to 10Gbps.  For that reason, many server IPs have disappeared, but new ones have also emerged.  can you update the server list please

**Comment by keeshux** [comment]
That's what "Refresh infrastructure" is meant for. Have you tried it?

**Comment by prentakias** [comment]
> That's what "Refresh infrastructure" is meant for. Have you tried it?

My bad.  I only refreshed the list of providers, I was under the impression that the lists of servers were also refreshed. Thx!
