### ISSUE TITLE
App icon not visible in the macos taskbar in dark theme

### ISSUE THREAD

**Issue by wookash** [passepartoutvpn/passepartout-apple#199]
The Passepartout icon is not visible on the taskbar on macos monterey with dark theme enabled and the VPN is disconnected. Is there a possibility to select custom icon color or switch the icon color to white in dark mode?

**Comment by keeshux** [comment]
Hi! I'm working on a new iconset as the issue is precisely related to using colors in the status bar. macOS expects icon behaviour to be color-agnostic, so I'm dropping colors in favor of different shapes instead. That will fix the issue for good.

**Comment by wookash** [comment]
Thanks. Is there and ETA on this feature?

**Comment by keeshux** [comment]
Immediately next version. Working on it with a designer.

**Comment by wookash** [comment]
Perfect. Thank you!
