### ISSUE TITLE
Edit Endpoint

### ISSUE THREAD

**Issue by cyayon** [passepartoutvpn/passepartout-apple#206]
Hello,

Is it possible to edit / override host endpoint inside the IOS app ?
I have also tried to provide multiple remote entries, but they do not appears in the endpoint param.
For protocol and port, it works as expected, but not for endpoints.

Do i missing something ?

Thanks.

**Comment by keeshux** [comment]
Is this from Reddit? By the way, not yet, but scheduled.

**Comment by cyayon** [comment]
thx

**Comment by juev** [comment]
It was be great, if we will have this function.
