### ISSUE TITLE
endless connection on mac os

### ISSUE THREAD

**Issue by MobiOS-21** [passepartoutvpn/passepartout-apple#210]
Hello. I want to run your project on mac os, but nothing works for me. I changed all bundle id , app group id, and on iOS it works fine, but on mac os it doesn’t connect to open vpn.
Below are screenshots with project settings, tell me, maybe I forgot to specify something?
**it's config file.**
<img width="735" alt="image" src="https://user-images.githubusercontent.com/31853009/151779938-1f5912a4-8391-4a7c-9b27-3d73b4aea544.png">
**It's launcher**
<img width="1049" alt="image" src="https://user-images.githubusercontent.com/31853009/151780097-b1243445-378f-4867-b541-dcac4bd10a03.png">
**It's tunnel**
<img width="1351" alt="image" src="https://user-images.githubusercontent.com/31853009/151780205-10161ba4-b818-4745-866f-cda5197ace21.png">
**It's macOS app**
<img width="1354" alt="image" src="https://user-images.githubusercontent.com/31853009/151780276-9497ea74-8891-4347-bc00-b24014c98cd3.png">
I also noticed the following, that after starting the application, it is written _💙 INFO GracefulVPN.prepare():57 - Preparing..._ 
But then in the iOS version it displays _DEBUG NetworkExtensionVPNProvider.vpnDidUpdate():197 - VPN status did change: 1_  but in the mac os version of such a log is not displayed

**Comment by keeshux** [comment]
Maybe check this: <img width="592" alt="Screen Shot 2022-01-31 at 12 39 55" src="https://user-images.githubusercontent.com/805724/151787667-2137d6f8-a28c-4235-8f34-6935d6449afe.png">

**Comment by MobiOS-21** [comment]
@keeshux I have a checkbox here =(

**Comment by keeshux** [comment]
By the way, in the Console you must debug VPN issues by filtering the tunnel app, not the main app.

**Comment by MobiOS-21** [comment]
@keeshux 
It's my debug.log file
<img width="1476" alt="image" src="https://user-images.githubusercontent.com/31853009/151789386-1809c5b7-9d8f-4eca-98ba-89491cabe001.png">

**Comment by MobiOS-21** [comment]
Anyone can help?

**Comment by keeshux** [comment]
Not an app issue anyway.
