### ISSUE TITLE
How to refresh data 

### ISSUE THREAD

**Issue by purepure** [passepartoutvpn/passepartout-apple#211]
Hey, this is great repo! You provide so much of features. Thank for this.
My question is: all the data from provider was updated via this https://github.com/passepartoutvpn/api 
How do I implement to get data from these source(nordvpn, pia,...) instead of via the above api?. Or simpler question is how do you get these data and submit to that api?

Thank for your hard work!

**Comment by keeshux** [comment]
Check this out: https://github.com/passepartoutvpn/api-source
