### ISSUE TITLE
Error establishing the tunnel (using ProtonVPN)

### ISSUE THREAD

**Issue by JoghurtConnaisseur** [passepartoutvpn/passepartout-apple#220]
When trying to establish a connection to the VPN via ProtonVPN, I get the following error:

Failed LINK read: Error Domain=NSPOSIXErrorDomain Code=40 "Message too long"

The VPN seems to be up, but there is no connection.

**Comment by c0d3h4x0r** [comment]
I'm having the same exact problem with OpenVPN.

**Comment by keeshux** [comment]
Duplicate of https://github.com/passepartoutvpn/tunnelkit/issues/239
