### ISSUE TITLE
Not working with Surfshark

### ISSUE THREAD

**Issue by tchlyah** [passepartoutvpn/passepartout-apple#221]
Surfshark is not working, it keep trying to connect then shows an error message: Failed Auth.

**Comment by keeshux** [comment]
Check your credentials I guess.

**Comment by tchlyah** [comment]
Don’t close it with even analyzing it and giving a chance to explain.

I’ve checked my credentials, they are correct, and workin perfectly with Surfshark application!

**Comment by tchlyah** [comment]
My passe word is randomly generated with 16 char and special characters (%, #, ^…). It may explain the issue.

**Comment by keeshux** [comment]
> Don’t close without even analyzing it and giving a chance to explain.
> 
> I’ve checked my credentials, they are correct, and working perfectly with Surfshark application!

But IIRC, SurfShark has specific credentials for OpenVPN.

**Comment by tchlyah** [comment]
You are right, I was not aware. Sorry for that.
Thanks

**Comment by keeshux** [comment]
> You are right, I was not aware. Sorry for that. Thanks

No worries, cheers to that.
