### ISSUE TITLE
In 2.0.0 is in Endpoint the endpoint missing

### ISSUE THREAD

**Issue by nielsk** [passepartoutvpn/passepartout-apple#224]
In 2.0.0 on iOS there is per connection a detail „endpoint“ with several technical details. 
In the technical details is the endpoint-IP missing. That should there be as well because I need it for example to decide between some VPNs because I didn’t name them very good but also use them rarely, thus I need to see which is the right one.

**Comment by keeshux** [comment]
Maybe the UI is not intuitive, for now toggle "Automatic" to see the list of endpoints.

**Comment by nielsk** [comment]
Thanks - no it is not intuitive. I didn't expect at all that "Automatic" hides that data.
