### ISSUE TITLE
Dock menu  doesnt synchronous when not minimize app

### ISSUE THREAD

**Issue by erayerdem** [passepartoutvpn/passepartout-apple#235]
I changing my vpn connection dev to prod bot dock state still looks dev, when I minimize the application it is syncing

![Screen Shot 2022-10-17 at 10 30 25](https://user-images.githubusercontent.com/42184225/196115672-e5491f47-1edf-48a8-9ffe-175b159d1571.png)

**Comment by keeshux** [comment]
App version?

**Comment by erayerdem** [comment]
2.0.0

**Comment by keeshux** [comment]
Let me know if 2.0.1 fixes it when it becomes available on the App Store (few hours I guess).
