### ISSUE TITLE
Ukrainian translation

### ISSUE THREAD

**Issue by josser** [passepartoutvpn/passepartout-apple#236]
First of all, I want to thank you for such cool app!

I'm not a professional translator but I know English, Russian and Ukrainian, 
Can I somehow help to add Ukrainian language translation?

**Comment by keeshux** [comment]
Hey @josser, I created a branch where you can find the 3 string files you need to translate, see 22767dc1e22362a59f85345d6c58c7efc42015e4 in particular.

Proceed this way:

- Fork the repo
- Check out `ukranian-l10ns` branch
- Push your modifications
- Create a pull request

I'll be more than happy to review and merge your contributions. Beware that we're talking about hundred of strings.

Thank you very much!

**Comment by josser** [comment]
Thank you! Already started translating w/o fork, but didn't know that there 3 files (thought about only one)

**Comment by keeshux** [comment]
> Thank you! Already started translating w/o fork, but didn't know that there 3 files (thought about only one)

- Intents.strings (a few ones)
- InfoPlist.strings (just 1 phrase)
- Localizable.strings (the main one)

**Comment by keeshux** [comment]
Goes without saying, you may go ahead and add yourself here, following format and alphabetical order:

https://github.com/passepartoutvpn/passepartout-apple#translations

**Comment by josser** [comment]
Finally finished PR https://github.com/passepartoutvpn/passepartout-apple/pull/243
