### ISSUE TITLE
Existing profiles with custom DNS not working after latest update

### ISSUE THREAD

**Issue by cclhk** [passepartoutvpn/passepartout-apple#237]
2.0.1 (3375)
iOS 15.7

I have several Mullvad OpenVPN profiles that work perfectly on 2.0.0 and earlier. All of these profiles have custom DoH settings applied in the 'Network settings' configuration section.

After the 2.0.1 update these profiles fail to connect, getting stuck in the 'Connecting' and 'Inactive' state.

Connection is OK if I turn off the custom DNS settings (i.e. set DNS to automatic). Changing the DoH settings or using a custom cleartext DNS like 1.1.1.1 do not resolve the issue.

Connection is also OK if I import a new profile then apply the DoH settings. Duplicating the existing profiles does not resolve the issue.

**Comment by keeshux** [comment]
Known regression, I'm working on it.

**Comment by keeshux** [comment]
https://github.com/passepartoutvpn/tunnelkit/issues/289

**Comment by keeshux** [comment]
I fixed this in the 2.0.2 patch, if you feel like testing it yourself, please send an email to issues@passepartoutvpn.app
