### ISSUE TITLE
The VPN disconnects and reconnect after a few seconds

### ISSUE THREAD

**Issue by dovanvu1792** [passepartoutvpn/passepartout-apple#249]
Hello. 
I tried this openvpn profile on android (OpenVPN offical app), everything works great.
But when running on ios, it is alway reconnected after seconds, this problem greatly affects the stability of the connection. Please see more on attach debug file
_[Version 2.0.2 (3395)]_
14:17:41 - Trigger shutdown (error: Error Domain=TunnelKitOpenVPN Code=103 "(null)")
14:17:41 - Session did stop with error: Error Domain=TunnelKitOpenVPN Code=103 "(null)"

[debug-20221115-142415.txt](https://github.com/passepartoutvpn/passepartout-apple/files/10010291/debug-20221115-142415.txt)

**Comment by keeshux** [comment]
https://passepartoutvpn.app/faq/#the-vpn-fails-with-auth-failed-or-immediately-disconnects-with-encryption-failed

**Comment by keeshux** [comment]
This is typically an encryption issue. The reason is however unclear from the log...

**Comment by keeshux** [comment]
Comments are not helpful if they don't come with the OpenVPN configuration attached. I'm closing this as stale until then.
