### ISSUE TITLE
Running up and down script after connection

### ISSUE THREAD

**Issue by TomFreudenberg** [passepartoutvpn/passepartout-apple#252]
Hi, I purchased today the full IOS and MacOS app and so far everything is working.

The only thing I miss, my scripts won't run on connection up and down on the Mac OSX.

```
script-security 2
up /Users/myuser/.local/bin/up-vpn.sh
down /Users/myuser/.local/bin/down-vpn.sh
```

It would be important to set some additional routes manually.

Thanks for your feedback.

P.S.: Additional feature request: show the IP address for an established connection in menubar (at the submenu where to press also for disconnect)

**Comment by keeshux** [comment]
1. The app cannot run scripts in general, that's why the up/down options are not implemented. Is it only routes what you're setting up in the scripts?
2. Fetching the IP address is a privacy concern

**Comment by TomFreudenberg** [comment]
Ok, you should mark the "not" possible / working parts better.

I had not bought the release when I was in knowledge former.

Things for NOT using Passepartout (not your fault !!!):

- Up/Down Script can not run (Tunnelblick has possibility)
- Can not start 2 or more VPN connections at the same time (WireGuard and Tunnelblick can)

Thanks for feedback
Tom
