### ISSUE TITLE
On Macos VPN is not passed to Android Emulator

### ISSUE THREAD

**Issue by BetterB0y** [passepartoutvpn/passepartout-apple#257]
Up to now I used Tunnelblick on MacOS beacuse it passes VPN connection to Android Emulator from Android Studio.

I would love to use your software, but it's not passing my vpn connection. Can you fix that?

**Comment by keeshux** [comment]
I’m afraid this might be beyond the scope of the app.

**Comment by BetterB0y** [comment]
Can you explain me than how tunnelblick is passing this?

**Comment by BetterB0y** [comment]
OpenVPN also has that problem and they also dismissed me

**Comment by keeshux** [comment]
Passepartout creates a native VPN profile through an Apple-vendored framework and that's basically it. I do not really touch the network interfaces or alter the low-level routing table, nor I need to for common use cases.

On the other hand, Tunnelblick uses the official OpenVPN client internally, which must be allowing for plenty of customizations. I don't really know how they accomplish what you're looking for, but at the same time I don't even know if it's possible given the way I deliver VPN connectivity in the first place. The two apps are not comparable.

**Comment by BetterB0y** [comment]
Okay. Thank you for explanation.
