### ISSUE TITLE
Can't assign requested address

### ISSUE THREAD

**Issue by rengen12** [passepartoutvpn/passepartout-apple#290]
Hi!
After update to v2.1.0  this error appeared in java related apps under vpn:
`Can't assign requested address: localhost 127.0.0.1:55403` 
or 
`Exception creating connection to: 127.0.0.1; nested exception is: 	java.net.BindException: Can't assign requested address.`

Tried [flush the routing table](https://www.ovpn.com/en/faq/troubleshooting/mac-cant-assign-requested-address-code49), didn't help. 
No errors found in app's error log.
Fixed when downgrating to v2.0.2

Macbook m1 pro, os ventura 13.3.1

**Comment by keeshux** [comment]
Please let me know if the 2.1.1 hotfix resolves your issue.

**Comment by rengen12** [comment]
yep, it works! Thanks
