### ISSUE TITLE
SideStore VPN profile with Passepartout does not work as with Wireguard iOS application.

### ISSUE THREAD

**Issue by hurryman2212** [passepartoutvpn/passepartout-apple#291]
With the Wireguard iOS applications, applying SideStore VPN profile does not alter the behavior with the internet connection (e.g. still able to connect external websites, no disabling Safari private relay).

However, with the latest Passepartout applications on the latest iOS version (16.4.1), applying it blocks all internet connections on all applications. It did not do that previously, but I am not sure which one of them (iOS 16.4.1 upgrade or the one of Passepartout updates) is the cause.

You can get the SideStore VPN profile with this [URL](https://github.com/SideStore/SideStore/releases/download/0.3.1/SideStore.conf), linked to the official repository of the SideStore iOS application.
I prefer to use Passepartout because it offers iOS shortcut functions to activate/deactivate the designated VPN profile so I can refresh SideStore with just one shortcut click, without manually triggering the VPN.

**Comment by keeshux** [comment]
Please let me know if the 2.1.1 hotfix resolves your issue.
