### ISSUE TITLE
Passepartout Not Connect on MacOS 13.3.1

### ISSUE THREAD

**Issue by m031n** [passepartoutvpn/passepartout-apple#293]
I have an OpenVPN file to connect, but after I update my mac to 13.3 it doesn’t connect on my mac, while it connects on my iPhone. I tried to uninstall profile, passepartout it self, remove and add profile again but the problem still remains. When I enabled it it stock on connecting, after that it shows disconnecting and after that show inactive, and this circle repeat for ever

**Comment by keeshux** [comment]
Let me know if the 2.1.1 hotfix resolves your issue.

**Comment by AltAdamNguyen** [comment]
I use version macOS 13.0.1 and version app 2.1.2 when try to connect to OpenVPN status shows like this:
![Screenshot 2023-08-22 at 16 00 45](https://github.com/passepartoutvpn/passepartout-apple/assets/83154328/e4ac35c0-d7d1-4d17-a380-6879bb6d9e32)

but in ios is a normal connection
