### ISSUE TITLE
[OVPN] Allow adding proxy pass domain wild cards

### ISSUE THREAD

**Issue by mietzen** [passepartoutvpn/passepartout-apple#296]
I was wondering if it might be possible to add (sub)domain wildcards like `*.example.com` to the OpenVPN proxy pass settings.

At the moment, entries with a * get marked red.
![Bildschirmfoto 2023-04-21 um 08 09 51](https://user-images.githubusercontent.com/31704359/233554114-9e0ee177-279e-4b6c-b8dd-1210bf3709e8.png)

**Comment by keeshux** [comment]
Would that be in the bypass list?

**Comment by keeshux** [comment]
Oh yeah, I saw your modified title now. The good thing is that TunnelKit already uses this:

https://developer.apple.com/documentation/networkextension/neproxysettings/1406687-exceptionlist

which in fact allows wildcards. So it's a matter of fixing the validation pattern for the field.

Thanks for your report!
