### ISSUE TITLE
Not working on macOS Sonoma using ethernet connection (Apple bug?)

### ISSUE THREAD

**Issue by alemar11** [passepartoutvpn/passepartout-apple#366]
# Summary

I've my machine (Mac mini M2) connected with an ethernet cable, the app gets stuck in the connecting phase (OpenVPN protocol).
Everything works fine if I switch to the wifi.

### Steps to reproduce

1. Use an ethernet connection on your Mac
2. Try to connect (I've tested only an OpenVPN profile)
3. The app won't connect

### What is the current bug behavior?

VPN won't connect unless the ethernet connection is disabled

### What is the expected correct behavior?

Successful connection 

### Relevant logs and/or screenshots

[See attachment logs.txt](https://github.com/passepartoutvpn/passepartout-apple/files/12879044/logs.txt)

**Comment by keeshux** [comment]
This smells like a macOS regression, could it be? The link below is only one of the many I get with a quick search:

https://droidwin.com/ethernet-not-working-on-macos-sonoma-how-to-fix/

**Comment by Ramsin** [comment]
@alemar11 is your firewall currently off? If so, can you try toggling it on, then off again, then try connecting over ethernet, please?

**Comment by alemar11** [comment]
@Ramsin it was off, I tried to turn it on and then off but it doesn't fix the problem.
Thanks for the suggestion though

**Comment by Ramsin** [comment]
@alemar11 Ok, that worked for me on my M1 Mac Mini, but now that I really reflected, I do know that I did several other things to try to get it to work....the following list is in as close to the order as I can remember.

Also, I should note that **_I'm running my own OpenVPN server at home. I'm not paying for a service._**

1. Removed and reinstalled the app
2. Removed and readded the VPN (from MacOS system settings, not Passepartout)
3. Removed and readded the network interface itself (in my case it was the Ethernet)
4. Toggled the Firewall (as previously mentioned, and that's what helped ultimately)

One more note. Shortly after, it all stopped (both on iOS and MacOS...which is still iOS as the app sees it) working again, with the same error you had in your log...restarting my _**VPN server**_ did the trick. Now, that's definitely an issue if you're paying for a service...unless you can convince them to reboot their server?...good luck!

**Comment by alemar11** [comment]
@keeshux @Ramsin macOS 14.1 (released yesterday) fixed the issue

**Comment by keeshux** [comment]
Thank you for the update!
