### ISSUE TITLE
LAN not reachable after a time

### ISSUE THREAD

**Issue by sadden3194** [passepartoutvpn/passepartout-apple#373]
# Summary
Wireguard VPN connection active (Fritzbox router as Wireguard server), but no connection to LAN after unspecifc time.

### Steps to reproduce
Import fritzbox wireguard config to the app.
My config looks like this:

```
[Interface]
PrivateKey = XXX
Address = 192.168.108.201/24
DNS = 192.168.108.250

[Peer]
PublicKey = XXX
PresharedKey = XXX
AllowedIPs = 192.168.108.0/24
Endpoint = vpn.myDomain.de:51888
PersistentKeepalive = 25
```

LAN: 192.168.108.0
DNS Server: 192.168.108.250 (Adguard)

### What is the current bug behavior?
I am using your app on iphones and ipads. VPN connection works on demand and works without problems.
But after a while, I can't reach my local area network and dns resolution doesn't work anymore (because I cant reach my dns server 192.168.108.250):

For example: I can ping 8.8.8.8 with a response, but if I ping google.de I get no response.
If I try to ping the device IP (192.168.108.201) - I get no response.

### Relevant logs and/or screenshots
I attached the logs
[debug-20231106-131555 2.txt](https://github.com/passepartoutvpn/passepartout-apple/files/13266756/debug-20231106-131555.2.txt)

**Comment by keeshux** [comment]
Uhm this seems out of the Passepartout scope, it's an inherent bug of WireGuard as I see it.
