### ISSUE TITLE
Wireguard: Default route set even when disabled in settings

### ISSUE THREAD

**Issue by kohlschuetter** [passepartoutvpn/passepartout-apple#443]
# Summary
I have a Wireguard connection that should only connect me with a single server.
I disable all settings under "Default Gateway" (Automatic, IPv4, IPv6 are all off).
However, the default route is still set, as one can see via `netstat -rlan`

### Steps to reproduce
Using Version 2.2.1 (3548)

1. Import WireGuard profile 
2. Disable "Automatic" default gateway
3. `netstat -rlan | grep default` to see current default gateways 
4. Enable Wireguard tunnel
5. `netstat -rlan | grep default` to see secondary default gateway 

### What is the current bug behavior?

A secondary default gateway is created.

### What is the expected correct behavior?

No changes should be made to the default gateway configuration.

### Possible fixes suggested remediation
Use Wireguard app

**Comment by keeshux** [comment]
This is out of scope, as I've just confirmed the same behavior with the official WireGuard app. Please report the issue there.
