### ISSUE TITLE
In-app Purchases

### ISSUE THREAD

**Issue by Dgram19** [passepartoutvpn/passepartout-apple#444]
Hi, convinced that I purchased in app on iphone both unlock for ios and macos, I found out that I made the purchase in app exclusively the iOS app. However, now there is no way to purchase in app the macOS program. Is there any solution?
s it possible to get a refund for the iOS app so that I can purchase both the iOS and macOS app? Thank you

**Comment by keeshux** [comment]
Yes, you may ask for a refund for the iOS purchase first, but it's iTunes you have to ask to:

https://reportaproblem.apple.com/?s=6

**Comment by Dgram19** [comment]
It doesn't allow me to request it.
