### ISSUE TITLE
Appstore - Not available in my country anymore

### ISSUE THREAD

**Issue by brokoler** [passepartoutvpn/passepartout-apple#451]
# Summary

Since yesterday Passetpartout disappeared from the german Appstore. I received the update to version 2.3.0 and a few hours later it was removed.

Maybe more countries are affected?

### Steps to reproduce

Try searching for Passetpartout, you receive no results.
Clicking on a direct link shows the message app is not available.

Would be great to see it back!

Kind regards

**Comment by keeshux** [comment]
This is the reason:

https://www.reddit.com/r/passepartout/comments/18zo6uj/comment/kgj0sfl/?utm_source=share&utm_medium=web2x&context=3

I'll push the hotfix tomorrow and the app will be back.
